require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 6
Metrics/ClassLength:
  Max: 100
RSpec/ExampleLength:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 32
Style/Documentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/models/concerns/belongs_to_non_db.rb'